export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const PUT_USERROLE_SUCCESS = "PUT_USERROLE_SUCCESS";

export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
export const PUT_CUSTOMER_SUCCESS = "PUT_CUSTOMER_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
